version: "1"

services:
  - type: web
    name: digital-market-space-backend
    runtime: node
    repo: https://github.com/zouk5574-stack/Digital-Market-Space-BACKEND-
    plan: free
    region: oregon
    branch: main
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: FEDAPAY_PUBLIC_KEY
        sync: false
      - key: FEDAPAY_SECRET_KEY
        sync: false